### PR TITLE
Switch to dune.3.8 to allow dune to run test partitions concurrently 

### PR DESCRIPTION
**Pull request by hhugo**
This is just a Draft because the two items below need to happen first.
- [x] https://github.com/ocaml/dune/pull/7012 needs to be merged.
- [x] dune 3.8 needs to be released https://github.com/ocaml/dune/milestone/44

This PR
1. upgrade the dune lang to 3.8
2. use ppxlib V2 api
3. make the ppx compute the partition name if not specified. (requires 2)
4. teach dune how to list partitions (requires 1)

This change should be enough to have tests run concurrently inside dune when using ppx_inline_test or ppx_expect.

### CODE REVIEW

**Comment by sliquister** [comment]
Hey! I'll take the ppx change, as that doesn't require a new version of dune.

**Comment by hhugo** [comment]
Rebased and signed commits

**Comment by hhugo** [comment]
The dune PR has been merged. Waiting for the next dune release

**Comment by hhugo** [comment]
Dune 3.8 is about to be released on opam https://github.com/ocaml/opam-repository/pull/23814

**Comment by hhugo** [comment]
I've rebased the PR

**Comment by hhugo** [comment]
Are there any known blocker for upgrading the dune lang version of Jane Street packages ?

**Comment by dkalinichenko-js** [comment]
Paging @ceastlund, but seems fine by me.

**Comment by hhugo** [comment]
I'm guessing dune files are still generated automatically on your side. If so, any news regarding bumping the dune lang version ?

**Comment by hhugo** [comment]
gentle ping

**Comment by dkalinichenko-js** [comment]
Hi! We found that we need to rework our code generator for dune files before we can switch to a recent language version, and it's unclear whether we'll do this in time for the next release. That said, I can manually port those changes to v0.16.1 if needed.

**Comment by hhugo** [comment]
>  it's unclear whether we'll do this in time for the next release

When do you expect the next release ?

> I can manually port those changes to v0.16.1 if needed.

It's going to be annoying if this change is "reverted" at every release. That said, having a minor v0.16 release would immediately benefit all ppx_inline_tests users so I'm all for it.

**Comment by dkalinichenko-js** [comment]
> When do you expect the next release ?

Around December-January.

I've submitted the release v0.16.1 with your change to the main opam repository. I'll keep this PR around as a reminder for fixing this issue on our side.

**Comment by hhugo** [comment]
Any progress on that front ?

**Comment by dkalinichenko-js** [comment]
Hi! The release v0.17 of our libraries will use Dune 3.11 and is under our review right now.

**Comment by hhugo** [comment]
Thanks.

**Pull request closed without merging**
